version: '3.8'

services:
  backend:
    build: 
      context: ./spring-backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db 
      MYSQL_PORT: 3306  
      MYSQL_DATABASE: mydatabase 
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 15s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./react-frontend/.env
    depends_on:
    - backend